// Code generated by "stringer -type=KeyPressed"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoOp-0]
	_ = x[Close-1]
	_ = x[Open-2]
	_ = x[Stop-3]
	_ = x[Update-4]
	_ = x[LearnOpen-5]
	_ = x[LearnClose-6]
	_ = x[LearnStop-7]
	_ = x[TestOpen-8]
	_ = x[TestClose-9]
	_ = x[TestStop-10]
	_ = x[SetOpen-11]
	_ = x[SetClose-12]
	_ = x[SetStop-13]
}

const _KeyPressed_name = "NoOpCloseOpenStopUpdateLearnOpenLearnCloseLearnStopTestOpenTestCloseTestStopSetOpenSetCloseSetStop"

var _KeyPressed_index = [...]uint8{0, 4, 9, 13, 17, 23, 32, 42, 51, 59, 68, 76, 83, 91, 98}

func (i KeyPressed) String() string {
	if i < 0 || i >= KeyPressed(len(_KeyPressed_index)-1) {
		return "KeyPressed(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyPressed_name[_KeyPressed_index[i]:_KeyPressed_index[i+1]]
}
