#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          wifi-connect
# Required-Stop:
# Default-Stop:
# Short-Description: Handles wifi connectivity.
# Description:       Presents a captive portal page to facilitate WIFI ssid discovery and connect. Not to be confused with the actual binary of wifi-connect, this here is the executable service
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    # make sure privileges don't persist across reboots
    if [ -d /var/lib/sudo ]
    then
                /home/pi/HomeGate/pi/system/periodoc-wifi-connect.sh &;
    fi
    ;;
  stop|reload|restart|force-reload|status)
    pkill -9 periodoc-wifi-connect
    ;;
  *)
    exit 1
    ;;
esac

exit 0

